server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway

ribbon: 
  eureka: 
    enabled: false


zuul:
  routes:
    department:
      path: /department/**
    employee:
      path: /employee/**
    organization:
      path: /organization/**
    environment:
      path: /environment/**


logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"